"""add threat intelligence table

Revision ID: 1ba3e6cc0caf
Revises: dbb248a54f87
Create Date: 2026-08-19 16:28:46.377289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba3e6cc0caf'
down_revision: Union[str, Sequence[str], None] = 'dbb248a54f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.String(length=100), nullable=False),
    sa.Column('ioc_value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_intelligence')
    # ### end Alembic commands ###
